"use client";

import * as React from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { CheckCircle2, Clock, FileText, Loader2, Upload, XCircle } from "lucide-react";

import { Button } from "@/components/ui/button";
import { submitArtifact, uploadArtifact } from "@/lib/api/artifacts";
import { qk } from "@/lib/api/query-keys";
import type { Artifact, ProjectId } from "@/lib/schemas";

/**
 * What the chat just produced, and where each file stands in the project's record.
 *
 * THIS CARD USED TO BE A LIST OF LINKS AND NOTHING ELSE, which made a working feature
 * look broken. An agent-generated document IS registered as a pending artifact the
 * moment it is written (`chat_artifacts.register_generated_file`), so it is already in
 * the Documents panel and already in Requests & Approvals — but the card said nothing,
 * so the obvious reading was that the file existed only in the chat and somebody still
 * had to file it by hand. That was the question this component was written to answer.
 *
 * MATCHED BY FILENAME, because that is the only field the two sides share. A chat
 * document knows its name and a download URL; the artifact row knows its title, which
 * is the same filename. There is no id in common — the chat list is in-memory and the
 * artifact row is a database row created independently.
 *
 * AND THE FALLBACK IS THE POINT. `register_generated_file` is deliberately best-effort:
 * a document that was generated and shown is not un-generated by a failure to record
 * it, so it swallows its own errors. The cost is a file that exists in the chat and
 * nowhere else, with nothing to say so. When no artifact matches, this offers to put it
 * in — which is the only recovery there has ever been, and previously required
 * downloading the file and uploading it again by hand.
 */

export interface GeneratedDoc {
  id: string;
  name?: string | null;
  /** Optional: the chat document type allows it to be absent. Without a URL there is
   *  nothing to open and nothing to fetch, so the row degrades to a plain name. */
  url?: string | null;
}

/** `null` while the artifact list is still loading — "not recorded" must not be
 *  guessed from an answer that has not arrived. */
type Standing = "draft" | "approved" | "pending" | "rejected" | "absent" | "unknown";

function matchFor(name: string, artifacts: Artifact[] | null): Artifact | undefined {
  return artifacts?.find((a) => a.title === name);
}

function standingOf(name: string, artifacts: Artifact[] | null): Standing {
  if (artifacts === null) return "unknown";
  const match = matchFor(name, artifacts);
  if (!match) return "absent";
  if (match.status === "draft") return "draft";
  if (match.status === "approved") return "approved";
  if (match.status === "rejected") return "rejected";
  return "pending";
}

const CHIP: Record<
  Exclude<Standing, "absent" | "unknown">,
  { label: string; icon: React.ComponentType<{ className?: string }>; className: string }
> = {
  draft: {
    // NEUTRAL. A draft is waiting on nobody — colouring it like pending is what made
    // every working iteration look like an outstanding task in somebody's queue.
    label: "Draft",
    icon: FileText,
    className: "border-border bg-muted text-muted-foreground",
  },
  approved: {
    label: "Approved",
    icon: CheckCircle2,
    className: "border-success/30 bg-success/10 text-success",
  },
  pending: {
    label: "Pending approval",
    icon: Clock,
    className: "border-warning/30 bg-warning/10 text-warning",
  },
  rejected: {
    label: "Rejected",
    icon: XCircle,
    className: "border-destructive/30 bg-destructive/10 text-destructive",
  },
};

export function GeneratedDocuments({
  documents,
  projectId,
  stage,
  artifacts,
  className,
}: {
  documents: GeneratedDoc[];
  projectId: ProjectId;
  /** Backend stage name — what the recovered upload is filed under. */
  stage: string;
  /** This project's artifacts, or null while they load. */
  artifacts: Artifact[] | null;
  className?: string;
}) {
  const queryClient = useQueryClient();
  const [busy, setBusy] = React.useState<string | null>(null);

  const add = useMutation({
    mutationFn: async (doc: GeneratedDoc) => {
      // FETCHED FROM THE SAME URL THE LINK USES. The bytes live under the `/generated`
      // static mount; there is no server-side "promote this chat document" route, and
      // adding one would need the file path, which only the agent process knows.
      if (!doc.url) throw new Error("That document has no file to add.");
      const res = await fetch(doc.url);
      if (!res.ok) throw new Error(`Couldn't read the generated file (${res.status}).`);
      const blob = await res.blob();
      const name = doc.name ?? "document";
      await uploadArtifact(projectId, new File([blob], name, { type: blob.type }), {
        stage,
        note: "Added from the agent's generated documents.",
      });
    },
    onMutate: (doc) => setBusy(doc.id),
    onSettled: () => setBusy(null),
    onSuccess: () => {
      toast.success("Added to Documents — waiting for approval");
      void queryClient.invalidateQueries({ queryKey: qk.artifacts.forProject(projectId) });
      void queryClient.invalidateQueries({ queryKey: qk.approvals.list({}) });
    },
    onError: (e: Error) => toast.error(e.message || "Couldn't add it to Documents"),
  });

  const raise_ = useMutation({
    mutationFn: async (doc: GeneratedDoc) => {
      const match = matchFor(doc.name ?? "document", artifacts);
      if (!match) throw new Error("That document is not in the project's record yet.");
      await submitArtifact(match.id);
    },
    onMutate: (doc) => setBusy(doc.id),
    onSettled: () => setBusy(null),
    onSuccess: () => {
      toast.success("Raised for approval");
      void queryClient.invalidateQueries({ queryKey: qk.artifacts.forProject(projectId) });
      void queryClient.invalidateQueries({ queryKey: qk.approvals.list({}) });
    },
    onError: (e: Error) => toast.error(e.message || "Couldn't raise it for approval"),
  });

  // THE LAST TEN FOR THIS STAGE, not just this conversation. `documents` is the open
  // session's list, so a file generated yesterday vanished from this card the moment the
  // page reloaded — while still sitting in the project's record, which made the card
  // look like the whole history when it was a keyhole onto it.
  //
  // Session documents come first and in their own order: they are what just happened,
  // and the reader is usually looking for the one the agent named a second ago.
  const seen = new Set(documents.map((d) => d.name ?? "document"));
  const recent: GeneratedDoc[] = (artifacts ?? [])
    .filter((a) => a.type !== "story" && !seen.has(a.title))
    .slice(0, Math.max(0, 10 - documents.length))
    .map((a) => ({ id: `artifact-${a.id}`, name: a.title, url: a.downloadUrl ?? null }));

  const rows = [...documents, ...recent];
  if (rows.length === 0) return null;

  return (
    <section className={className}>
      <h3 className="text-muted-foreground mb-2 text-xs font-semibold uppercase tracking-wider">
        Generated documents
      </h3>
      <ul className="space-y-1.5">
        {rows.map((d) => {
          const name = d.name ?? "document";
          const standing = standingOf(name, artifacts);
          const chip = standing === "absent" || standing === "unknown" ? null : CHIP[standing];
          const Icon = chip?.icon;
          return (
            <li key={d.id} className="flex flex-wrap items-center gap-2">
              {d.url ? (
                <a
                  href={d.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-info inline-flex items-center gap-1.5 text-sm hover:underline"
                >
                  <FileText className="size-3.5" aria-hidden />
                  {name}
                </a>
              ) : (
                <span className="text-muted-foreground inline-flex items-center gap-1.5 text-sm">
                  <FileText className="size-3.5" aria-hidden />
                  {name}
                </span>
              )}

              {chip && Icon && (
                <span
                  className={`inline-flex shrink-0 items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-medium ${chip.className}`}
                  title={
                    standing === "pending"
                      ? "Already in the project's Documents, waiting for an owner to accept it."
                      : undefined
                  }
                >
                  <Icon className="size-3" aria-hidden />
                  {chip.label}
                </span>
              )}

              {/* THE ASK, and it is the only place one is made. An agent records what
                  it produces as a draft — ask for three passes at a document and two of
                  them are dead the moment the third exists — so nothing reaches an
                  approver until somebody points at one. */}
              {standing === "draft" && (
                <Button
                  size="sm"
                  variant="outline"
                  className="h-6 px-2 text-[11px]"
                  disabled={busy === d.id}
                  onClick={() => raise_.mutate(d)}
                >
                  {busy === d.id ? (
                    <Loader2 className="size-3 animate-spin" aria-hidden />
                  ) : (
                    <Upload className="size-3" aria-hidden />
                  )}
                  Raise for approval
                </Button>
              )}

              {/* ONLY WHEN IT IS GENUINELY ABSENT. Offering this beside a document that
                  is already recorded would invite a duplicate row and teach people that
                  the automatic path cannot be trusted. */}
              {standing === "absent" && d.url && (
                <Button
                  size="sm"
                  variant="outline"
                  className="h-6 px-2 text-[11px]"
                  disabled={busy === d.id}
                  onClick={() => add.mutate(d)}
                >
                  {busy === d.id ? (
                    <Loader2 className="size-3 animate-spin" aria-hidden />
                  ) : (
                    <Upload className="size-3" aria-hidden />
                  )}
                  Add to Documents
                </Button>
              )}
            </li>
          );
        })}
      </ul>
    </section>
  );
}
