import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const config = [
  ...compat.extends(
    "next/core-web-vitals",
    "next/typescript",
    "plugin:storybook/recommended",
  ),
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "react/self-closing-comp": "warn",
      "prefer-const": "error",
      /**
       * `null: "ignore"` permits the deliberate `x != null` / `x == null`
       * idiom, which tests for null AND undefined in one comparison.
       *
       * This is not a relaxation: every other loose comparison is still an
       * error. Rewriting `!= null` to `!== null` would be a behaviour change
       * — `undefined` would stop being caught — so the codebase's existing
       * uses are correct and the rule was simply too strict for them.
       */
      eqeqeq: ["error", "always", { null: "ignore" }],
    },
  },
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      "storybook-static/**",
      "playwright-report/**",
      "test-results/**",
      "next-env.d.ts",
      // Auto-generated by MSW — not hand-authored code
      "public/mockServiceWorker.js",
    ],
  },
];

export default config;
