// @vitest-environment jsdom
import * as React from "react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import { GeneratedDocuments } from "@/components/app/generated-documents";
import type { Artifact, ProjectId } from "@/lib/schemas";

/**
 * The "Generated documents" card says where each file stands.
 *
 * THE CONFUSION IT EXISTS TO END. An agent-generated document is registered as a
 * PENDING artifact the moment it is written, so it is already in the Documents panel
 * and already in Requests & Approvals. The card showed a bare link and nothing else,
 * so the only available reading was that the file lived in the chat and somebody still
 * had to file it by hand — which is exactly what was asked. Nothing was broken; the
 * screen just never said so.
 *
 * THE TRAP THIS AVOIDS is offering "Add to Documents" next to a document that is
 * already pending. That invites a duplicate row and teaches people the automatic path
 * cannot be trusted — so the button appears ONLY when no artifact matches, and never
 * merely because the artifact list has not arrived yet.
 */

const PROJECT = "p-1" as ProjectId;

function doc(name: string) {
  return { id: `d-${name}`, name, url: `http://localhost/generated/${name}` };
}

function artifact(title: string, status: string): Artifact {
  return { title, status } as Artifact;
}

function renderCard(documents: ReturnType<typeof doc>[], artifacts: Artifact[] | null) {
  const qc = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return render(
    <QueryClientProvider client={qc}>
      <GeneratedDocuments
        documents={documents}
        projectId={PROJECT}
        stage="requirements"
        artifacts={artifacts}
      />
    </QueryClientProvider>,
  );
}

afterEach(cleanup);

describe("what the card says about a generated document", () => {
  it("shows it is already pending approval", () => {
    /** THE HEADLINE, and the whole reason for the component: url_shortener_brd.docx was
     *  awaiting approval the entire time and the card said nothing. */
    renderCard([doc("url_shortener_brd.docx")], [
      artifact("url_shortener_brd.docx", "awaiting_approval"),
    ]);

    expect(screen.getByText(/Pending approval/i)).toBeTruthy();
    expect(screen.queryByRole("button", { name: /Add to Documents/i })).toBeNull();
  });

  it("shows it as approved once an owner accepts it", () => {
    renderCard([doc("brd.docx")], [artifact("brd.docx", "approved")]);

    expect(screen.getByText(/^Approved$/i)).toBeTruthy();
    expect(screen.queryByRole("button", { name: /Add to Documents/i })).toBeNull();
  });

  it("offers to add one that was never recorded", () => {
    /** `register_generated_file` is deliberately best-effort — a generated document is
     *  not un-generated by a failure to record it — so a file can exist in the chat and
     *  nowhere else. This is the only recovery, and it used to mean downloading the
     *  file and uploading it again by hand. */
    renderCard([doc("orphan.docx")], []);

    expect(screen.getByRole("button", { name: /Add to Documents/i })).toBeTruthy();
  });

  it("offers nothing while the artifact list is still loading", () => {
    /** NON-VACUITY on the distinction that matters: "not recorded" must not be guessed
     *  from an answer that has not arrived. Treating `null` as an empty list would flash
     *  an Add button beside every document on every page load, and clicking it would
     *  duplicate one already filed. */
    renderCard([doc("brd.docx")], null);

    expect(screen.queryByRole("button", { name: /Add to Documents/i })).toBeNull();
    expect(screen.queryByText(/Pending approval/i)).toBeNull();
  });

  it("matches by filename, which is the only field the two sides share", () => {
    /** The chat list is in-memory with its own ids; the artifact is a database row
     *  created independently. A near-miss on the name is a different document.
     *
     *  Scoped to the row, because `brd-v2.docx` now also appears as a history entry —
     *  a page-wide "is Approved anywhere" query would find that one and pass for the
     *  wrong reason. */
    renderCard([doc("brd.docx")], [artifact("brd-v2.docx", "approved")]);

    const row = screen.getByText("brd.docx").closest("li")!;
    expect(row.textContent).toContain("Add to Documents");
    expect(row.textContent).not.toContain("Approved");
  });

  it("offers to raise a draft, and only a draft", () => {
    /** THE POINT OF THE DRAFT STATE. An agent records what it produces; asking for a
     *  decision is a separate act, so nothing reaches an approver until somebody points
     *  at one. Ask for three passes and two are dead by the time the third exists. */
    renderCard([doc("brd.docx")], [artifact("brd.docx", "draft")]);

    expect(screen.getByText(/^Draft$/i)).toBeTruthy();
    expect(screen.getByRole("button", { name: /Raise for approval/i })).toBeTruthy();
    expect(screen.queryByRole("button", { name: /Add to Documents/i })).toBeNull();
  });

  it("does not offer to raise something already pending", () => {
    /** NON-VACUITY: the button follows the state rather than appearing on everything.
     *  Raising a pending document again would ask for a decision already asked for. */
    renderCard([doc("brd.docx")], [artifact("brd.docx", "awaiting_approval")]);

    expect(screen.queryByRole("button", { name: /Raise for approval/i })).toBeNull();
    expect(screen.getByText(/Pending approval/i)).toBeTruthy();
  });
});

describe("the history beyond this chat session", () => {
  it("lists recent documents the open session did not produce", () => {
    /** `documents` is the OPEN session's list, so a file generated yesterday vanished
     *  from this card on reload while still sitting in the project's record — the card
     *  looked like the whole history when it was a keyhole onto it. */
    renderCard([doc("today.docx")], [
      artifact("yesterday.docx", "approved"),
      artifact("last-week.pptx", "draft"),
    ]);

    expect(screen.getByText("yesterday.docx")).toBeTruthy();
    expect(screen.getByText("last-week.pptx")).toBeTruthy();
  });

  it("does not list a document twice when it is in both", () => {
    /** The session document and its artifact row are the same file; showing both would
     *  read as two documents with the same name. */
    renderCard([doc("brd.docx")], [artifact("brd.docx", "draft")]);

    expect(screen.getAllByText("brd.docx")).toHaveLength(1);
  });

  it("caps the card at ten rows", () => {
    /** A "recent" list that grows without bound stops being recent. */
    const many = Array.from({ length: 25 }, (_, i) => artifact(`doc-${i}.docx`, "approved"));
    renderCard([doc("today.docx")], many);

    expect(screen.getAllByRole("listitem")).toHaveLength(10);
  });

  it("still names a document that has no file behind it", () => {
    /** The chat document type allows a missing url. It degrades to a plain name rather
     *  than a dead link, and offers no Add button — there would be nothing to fetch. */
    const qc = new QueryClient({ defaultOptions: { queries: { retry: false } } });
    render(
      <QueryClientProvider client={qc}>
        <GeneratedDocuments
          documents={[{ id: "d-1", name: "no-file.docx", url: null }]}
          projectId={PROJECT}
          stage="requirements"
          artifacts={[]}
        />
      </QueryClientProvider>,
    );

    expect(screen.getByText("no-file.docx")).toBeTruthy();
    expect(screen.queryByRole("link")).toBeNull();
    expect(screen.queryByRole("button", { name: /Add to Documents/i })).toBeNull();
  });
});
