"""Per-session capture of the last unit-testing run so the gated 'Open tests PR'
button (a separate request, after the run) can push the generated unit-test folder
to ADO.

The run's temp clone is deleted at finalize (cleanup_workspace), so we capture the
generated test file CONTENTS here (while work_dir still exists) and re-clone the
base branch fresh at PR time. Mirrors the deployment/documentation agents' pattern.
"""
from __future__ import annotations

import os
import threading
from typing import Dict, Optional

_lock = threading.Lock()
_store: Dict[str, dict] = {}


def set_unit_run(session_id: str, data: dict) -> None:
    with _lock:
        _store[str(session_id)] = data


def get_unit_run(session_id: str) -> Optional[dict]:
    with _lock:
        return _store.get(str(session_id))


def update_unit_run(session_id: str, **fields) -> None:
    with _lock:
        if str(session_id) in _store:
            _store[str(session_id)].update(fields)


def _collect_generated_files(state) -> list[dict]:
    """Gather generated test files as [{path (repo-relative), contents}] from the
    run state, reading from work_dir before it is cleaned up."""
    work_dir = state.get("work_dir")
    if not work_dir or not os.path.isdir(work_dir):
        return []
    paths: list[str] = []
    for s in (state.get("generated_test_sets") or []):
        if isinstance(s, dict):
            if s.get("test_file_paths"):
                paths.extend(s["test_file_paths"])
            elif s.get("test_file_path"):
                paths.append(s["test_file_path"])
    out: list[dict] = []
    seen: set[str] = set()
    for ap in paths:
        try:
            if not ap or not os.path.isfile(ap):
                continue
            rel = os.path.relpath(ap, work_dir).replace("\\", "/")
            if rel in seen or rel.startswith(".."):
                continue
            seen.add(rel)
            with open(ap, "r", encoding="utf-8", errors="replace") as f:
                out.append({"path": rel, "contents": f.read()})
        except Exception:
            continue
    return out


def _coverage_md(coverage: Optional[dict], results: Optional[dict], files: list[dict]) -> str:
    lines = ["# Test Coverage", ""]
    if coverage:
        pct = coverage.get("coverage_pct")
        stmts = coverage.get("statements")
        missed = coverage.get("missed")
        covered = (stmts - missed) if (isinstance(stmts, int) and isinstance(missed, int)) else None
        lines.append(f"**Line coverage:** {pct:.1f}%" if isinstance(pct, (int, float)) else "**Line coverage:** n/a")
        if covered is not None:
            lines.append(f"- Statements: {stmts} · Covered: {covered} · Missed: {missed}")
        if coverage.get("branch_coverage_pct") is not None:
            lines.append(f"- Branch coverage: {coverage['branch_coverage_pct']:.1f}%")
        lines.append("")
    if results:
        lines.append(
            f"**Tests:** {results.get('total', 0)} total · "
            f"{results.get('passed', 0)} passed · {results.get('failed', 0)} failed"
        )
        lines.append("")
    if files:
        lines.append("## Generated test files")
        for f in files:
            lines.append(f"- `{f['path']}`")
        lines.append("")
    lines.append("_Generated by the SDLC Testing agent._")
    return "\n".join(lines)


def capture(session_id: str, state, artifact) -> None:
    """Record the unit run into the store (best-effort; never raises into the run)."""
    try:
        sel = [str(x).lower() for x in (state.get("selected_test_types") or [])]
        # Only capture when this run was a unit run (or unscoped, which defaults to unit-style code tests).
        if sel and "unit" not in sel:
            return
        files = _collect_generated_files(state)
        if not files:
            return
        coverage = None
        cov = getattr(artifact, "coverage", None)
        if cov is not None:
            coverage = {
                "coverage_pct": getattr(cov, "coverage_pct", 0.0),
                "statements": getattr(cov, "statements", 0),
                "missed": getattr(cov, "missed", 0),
                "branch_coverage_pct": getattr(cov, "branch_coverage_pct", None),
            }
        results = None
        execu = getattr(artifact, "test_execution", None)
        if execu is not None:
            results = {
                "total": getattr(execu, "total", 0),
                "passed": getattr(execu, "passed", 0),
                "failed": getattr(execu, "failed", 0),
                "skipped": getattr(execu, "skipped", 0),
            }
        ct = state.get("clone_target") or {}
        set_unit_run(session_id, {
            "tenant_id": state.get("tenant_id") or "",
            "clone_target": {"project": ct.get("project"), "repo": ct.get("repo"),
                             "branch": ct.get("branch") or state.get("pr_branch")},
            "generated_files": files,
            "coverage": coverage,
            "results": results,
            "coverage_md": _coverage_md(coverage, results, files),
            "pr_url": None,
        })
    except Exception:
        pass
