"""baseline: redesigned schema with scope-typed role bindings

Replaces the 39 migrations that built the previous schema. Three things happen here
that a plain autogenerate cannot produce, and all three are load-bearing:

  1. Row-level security. Every tenant-scoped table gets ENABLE + two policies + FORCE.
     FORCE on its own leaves a table wide open, so none of the four statements may be
     skipped. The previous schema protected 21 tables while the ORM constant claimed
     14 — that gap is closed here by driving both from shared.models.orm._RLS_TABLES.

  2. The RBAC catalog seed. roles / permissions / role_permissions are global (no
     tenant_id, no RLS) and are seeded from shared.authz.permissions, which mirrors
     frontend/lib/auth/role-permissions.ts. Seeding from the same module the app reads
     is what makes test_enterprise_rbac_catalog's drift check meaningful.

  3. Nothing is seeded into an RLS table. FORCE applies to the migration role too, so
     an INSERT there would fail the WITH CHECK policy unless the tenant GUC were set.
     role_bindings therefore starts empty — deny-by-default. The first binding comes
     from shared/authz/grant.py, which sets the GUC.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-11

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from shared.authz.permissions import _ROLE_PERMISSIONS, ALL_PERMISSIONS, ROLE_TIER
from shared.models.orm import _RLS_TABLES

# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# A short human label per role, stored in roles.description.
_ROLE_DESCRIPTIONS: dict[str, str] = {
    "org_admin": "Organization Admin — org-wide governance, onboards business units",
    "bu_admin": "Business Unit Admin — runs one unit, assigns roles within it",
    "contributor": "Contributor — onboarded, awaiting a real role from the unit admin",
    "project_admin": "Project Admin — owns a project and its members",
    "ba": "Business Analyst — owns requirements",
    "architect": "Architect — owns design and development approval",
    "developer": "Developer — builds",
    "qa": "QA Engineer — owns testing approval",
    "security_engineer": "Security Engineer — security review and audit visibility",
    "devops_engineer": "DevOps Engineer — owns deployment approval",
    "data_engineer": "Data Engineer — data pipelines",
    "scrum_master": "Scrum Master — process and visibility, no approval authority",
    "custom": "Custom — tenant-defined, permissions attached separately",
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_call_logs_created_at'), 'agent_call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_call_logs_run_id'), 'agent_call_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_call_logs_tenant_id'), 'agent_call_logs', ['tenant_id'], unique=False)
    op.create_table('agent_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('prompt_prepend', sa.Text(), nullable=True),
    sa.Column('prompt_append', sa.Text(), nullable=True),
    sa.Column('enabled_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disabled_curated', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_doc_summaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_contract_extra', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'scope', 'scope_id', 'version', name='uq_agent_profile_scope_version')
    )
    op.create_index(op.f('ix_agent_profiles_agent_id'), 'agent_profiles', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_profiles_tenant_id'), 'agent_profiles', ['tenant_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('agent_type', sa.String(length=50), server_default='requirements', nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('requirements_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('design_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('development_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('testing_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('code_review_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('security_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deployment_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('documentation_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_handoff_event', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_stage', sa.String(length=50), server_default='ingestion', nullable=True),
    sa.Column('artifact_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_agent_sessions_tenant_id'), 'agent_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('agent_skill_toggles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('skill_key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'scope', 'scope_id', 'origin', 'skill_key', name='uq_agent_skill_toggle')
    )
    op.create_index(op.f('ix_agent_skill_toggles_tenant_id'), 'agent_skill_toggles', ['tenant_id'], unique=False)
    op.create_table('agent_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('skill_key', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('when_to_use', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('runtime', sa.String(length=8), server_default='llm', nullable=False),
    sa.Column('origin', sa.String(length=16), server_default='custom', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'scope', 'scope_id', 'skill_key', 'version', name='uq_agent_skill_version')
    )
    op.create_index(op.f('ix_agent_skills_agent_id'), 'agent_skills', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_skills_tenant_id'), 'agent_skills', ['tenant_id'], unique=False)
    op.create_table('app_secrets',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('ciphertext', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'ref')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'scope_type', 'scope_id', name='uq_conversation_scope')
    )
    op.create_index('ix_conv_user_agent', 'conversation_sessions', ['tenant_id', 'created_by', 'agent_id', 'project_id', 'status', 'updated_at'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_run_id'), 'conversation_sessions', ['run_id'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_tenant_id'), 'conversation_sessions', ['tenant_id'], unique=False)
    op.create_table('custom_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_custom_role_tenant_name')
    )
    op.create_index(op.f('ix_custom_roles_tenant_id'), 'custom_roles', ['tenant_id'], unique=False)
    op.create_table('dev_workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('ado_project', sa.String(length=200), nullable=False),
    sa.Column('repo_name', sa.String(length=200), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=False),
    sa.Column('remote_url', sa.String(length=500), nullable=False),
    sa.Column('work_dir', sa.String(length=500), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pulling', nullable=False),
    sa.Column('pulled_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id', name='uq_dev_workspace_project')
    )
    op.create_index(op.f('ix_dev_workspaces_tenant_id'), 'dev_workspaces', ['tenant_id'], unique=False)
    op.create_table('eval_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_records_created_at'), 'eval_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_eval_records_run_id'), 'eval_records', ['run_id'], unique=False)
    op.create_index(op.f('ix_eval_records_tenant_id'), 'eval_records', ['tenant_id'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('server_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('transport', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('command', sa.String(length=512), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('env_vars_secret_ref', sa.String(length=255), nullable=True),
    sa.Column('headers_secret_ref', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('allowed_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tools_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'server_name', name='uq_mcp_server_tenant_name')
    )
    op.create_index(op.f('ix_mcp_servers_tenant_id'), 'mcp_servers', ['tenant_id'], unique=False)
    op.create_table('model_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=False),
    sa.Column('api_base', sa.String(length=512), nullable=True),
    sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='unverified', nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_providers_tenant_id'), 'model_providers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_model_providers_workspace_id'), 'model_providers', ['workspace_id'], unique=False)
    op.create_table('orchestrator_state',
    sa.Column('chat_session_id', sa.String(length=64), nullable=False),
    sa.Column('current_active_agent', sa.String(length=50), nullable=True),
    sa.Column('current_batch_id', sa.String(length=64), nullable=True),
    sa.Column('pending_user_gate', sa.String(length=50), nullable=True),
    sa.Column('last_handoff_event', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_session_id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('suspended', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('monthly_budget_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('platform_users',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('platform_role', sa.String(length=32), server_default='platform_admin', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('usage_monthly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.String(length=6), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=6), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'scope', 'scope_id', 'month', name='uq_usage_monthly_scope_month')
    )
    op.create_index(op.f('ix_usage_monthly_tenant_id'), 'usage_monthly', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('author_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=32), server_default='markdown', nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_message_session_seq')
    )
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_tenant_id'), 'conversation_messages', ['tenant_id'], unique=False)
    op.create_table('custom_role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_role_id', sa.UUID(), nullable=False),
    sa.Column('permission_name', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['custom_role_id'], ['custom_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_name'], ['permissions.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_role_id', 'permission_name', name='uq_custom_role_perm')
    )
    op.create_index(op.f('ix_custom_role_permissions_custom_role_id'), 'custom_role_permissions', ['custom_role_id'], unique=False)
    op.create_index(op.f('ix_custom_role_permissions_tenant_id'), 'custom_role_permissions', ['tenant_id'], unique=False)
    op.create_table('model_offerings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('input_price_per_million', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('output_price_per_million', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('tpm_limit', sa.Integer(), nullable=True),
    sa.Column('cost_limit_usd', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_id', name='uq_offering_provider_model')
    )
    op.create_index(op.f('ix_model_offerings_provider_id'), 'model_offerings', ['provider_id'], unique=False)
    op.create_index(op.f('ix_model_offerings_tenant_id'), 'model_offerings', ['tenant_id'], unique=False)
    op.create_table('role_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('scope_kind', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=True),
    sa.Column('custom_role_id', sa.UUID(), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope_kind IN ('organization', 'business_unit', 'project')", name='ck_role_binding_scope_kind'),
    sa.CheckConstraint("status IN ('active', 'invited', 'deactivated')", name='ck_role_binding_status'),
    sa.CheckConstraint("tier IS NULL OR tier IN ('governance', 'delivery')", name='ck_role_binding_tier'),
    sa.CheckConstraint('(role_name IS NOT NULL AND custom_role_id IS NULL) OR (role_name IS NULL AND custom_role_id IS NOT NULL)', name='ck_role_binding_exactly_one_role'),
    sa.ForeignKeyConstraint(['custom_role_id'], ['custom_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope_kind', 'scope_id', 'role_name', name='uq_role_binding_scope_role')
    )
    op.create_index(op.f('ix_role_bindings_custom_role_id'), 'role_bindings', ['custom_role_id'], unique=False)
    op.create_index(op.f('ix_role_bindings_scope_id'), 'role_bindings', ['scope_id'], unique=False)
    op.create_index(op.f('ix_role_bindings_scope_kind'), 'role_bindings', ['scope_kind'], unique=False)
    op.create_index(op.f('ix_role_bindings_tenant_id'), 'role_bindings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_role_bindings_user_id'), 'role_bindings', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('permission_name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['permission_name'], ['permissions.name'], ),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('role_name', 'permission_name')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('business_unit', sa.String(length=120), nullable=True),
    sa.Column('cost_center', sa.String(length=64), nullable=True),
    sa.Column('monthly_budget_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_classification', sa.String(length=20), server_default='internal', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('provider_kind', sa.String(length=50), server_default='azure_devops', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mcp_servers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('connectors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_budget_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('workspace_connectors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'kind', name='uq_workspace_connector_kind')
    )
    op.create_index(op.f('ix_workspace_connectors_tenant_id'), 'workspace_connectors', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workspace_connectors_workspace_id'), 'workspace_connectors', ['workspace_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), server_default='requirements', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('offering_id', sa.String(length=36), nullable=True),
    sa.Column('model_display_name', sa.String(length=255), nullable=True),
    sa.Column('trigger', sa.String(length=50), server_default='manual', nullable=False),
    sa.Column('requirements_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requirements_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('design_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('development_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('testing_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('code_review_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('security_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deployment_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('documentation_artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('gate_pending', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=255), nullable=True),
    sa.Column('temporal_run_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_runs_temporal_workflow_id'), 'runs', ['temporal_workflow_id'], unique=False)
    op.create_index(op.f('ix_runs_tenant_id'), 'runs', ['tenant_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('blob_url', sa.Text(), nullable=True),
    sa.Column('blob_path', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_run_id'), 'artifacts', ['run_id'], unique=False)
    op.create_index(op.f('ix_artifacts_tenant_id'), 'artifacts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Row-level security (see module docstring, point 1).
    #
    # `current_setting(..., true)` returns NULL when the GUC is unset rather than
    # raising — so a connection that never set app.current_tenant_id sees NO rows
    # instead of leaking. FORCE subjects the table owner to the policies too.
    # ------------------------------------------------------------------
    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)"
        )
        # The previous schema gave mcp_servers and workspace_connectors a USING policy
        # but no WITH CHECK, leaving INSERTs into them unconstrained by tenant. Every
        # table gets both halves here.
        op.execute(
            f"CREATE POLICY tenant_isolation_insert ON {table} "
            f"WITH CHECK (tenant_id = current_setting('app.current_tenant_id', true)::uuid)"
        )
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")

    # ------------------------------------------------------------------
    # RBAC catalog seed (see module docstring, point 2).
    # Global tables — no tenant_id, no RLS — so a plain migration INSERT is fine.
    # ------------------------------------------------------------------
    roles_tbl = sa.table(
        "roles", sa.column("name", sa.String), sa.column("description", sa.String)
    )
    perms_tbl = sa.table("permissions", sa.column("name", sa.String))
    role_perms_tbl = sa.table(
        "role_permissions",
        sa.column("role_name", sa.String),
        sa.column("permission_name", sa.String),
    )

    op.bulk_insert(
        roles_tbl,
        [
            {"name": role, "description": _ROLE_DESCRIPTIONS.get(role, role)}
            for role in sorted(_ROLE_PERMISSIONS)
        ],
    )
    # The permissions table must hold every string a role grant can reference, wildcards
    # included. ALL_PERMISSIONS is the *grantable leaf* catalog — what the custom-role
    # builder offers a tenant to pick from — and deliberately excludes admin:*. But
    # role_permissions.permission_name is an FK onto this table, and resolve_permissions_
    # for_user reads the user's permissions straight out of it. Seeding only the leaves
    # left org_admin with an empty grant set, so a newly registered org admin resolved to
    # zero permissions and could do nothing at all.
    _WILDCARDS = ["admin:*"]
    op.bulk_insert(perms_tbl, [{"name": p} for p in ALL_PERMISSIONS + _WILDCARDS])

    grants = [
        {"role_name": role, "permission_name": perm}
        for role, perms in sorted(_ROLE_PERMISSIONS.items())
        for perm in perms
    ]
    # Every granted string must exist in the permissions table or the FK rejects the row.
    _known = set(ALL_PERMISSIONS) | set(_WILDCARDS)
    unknown = {g["permission_name"] for g in grants} - _known
    assert not unknown, f"role grants reference uncatalogued permissions: {sorted(unknown)}"
    op.bulk_insert(role_perms_tbl, grants)



def downgrade() -> None:
    """Downgrade schema."""
    # Drop the policies before the tables. DROP TABLE would take the policies with it,
    # but being explicit keeps a partial downgrade from leaving orphaned policy objects
    # if a later statement fails.
    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_insert ON {table}")
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # Clear the catalog seed, dependants first. roles.name and permissions.name are
    # referenced by role_permissions AND by the two tenant-scoped tables (role_bindings,
    # custom_role_permissions), so any real data in those blocks the catalog delete —
    # a downgrade run against a database that has been used, rather than a fresh one,
    # fails here otherwise.
    op.execute("DELETE FROM custom_role_permissions")
    op.execute("DELETE FROM role_bindings")
    op.execute("DELETE FROM role_permissions")
    op.execute("DELETE FROM permissions")
    op.execute("DELETE FROM roles")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_tenant_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_run_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_runs_tenant_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_temporal_workflow_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_workspace_connectors_workspace_id'), table_name='workspace_connectors')
    op.drop_index(op.f('ix_workspace_connectors_tenant_id'), table_name='workspace_connectors')
    op.drop_table('workspace_connectors')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_role_bindings_user_id'), table_name='role_bindings')
    op.drop_index(op.f('ix_role_bindings_tenant_id'), table_name='role_bindings')
    op.drop_index(op.f('ix_role_bindings_scope_kind'), table_name='role_bindings')
    op.drop_index(op.f('ix_role_bindings_scope_id'), table_name='role_bindings')
    op.drop_index(op.f('ix_role_bindings_custom_role_id'), table_name='role_bindings')
    op.drop_table('role_bindings')
    op.drop_index(op.f('ix_model_offerings_tenant_id'), table_name='model_offerings')
    op.drop_index(op.f('ix_model_offerings_provider_id'), table_name='model_offerings')
    op.drop_table('model_offerings')
    op.drop_index(op.f('ix_custom_role_permissions_tenant_id'), table_name='custom_role_permissions')
    op.drop_index(op.f('ix_custom_role_permissions_custom_role_id'), table_name='custom_role_permissions')
    op.drop_table('custom_role_permissions')
    op.drop_index(op.f('ix_conversation_messages_tenant_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_monthly_tenant_id'), table_name='usage_monthly')
    op.drop_table('usage_monthly')
    op.drop_table('roles')
    op.drop_index(op.f('ix_platform_users_email'), table_name='platform_users')
    op.drop_table('platform_users')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('orchestrator_state')
    op.drop_index(op.f('ix_model_providers_workspace_id'), table_name='model_providers')
    op.drop_index(op.f('ix_model_providers_tenant_id'), table_name='model_providers')
    op.drop_table('model_providers')
    op.drop_index(op.f('ix_mcp_servers_tenant_id'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index(op.f('ix_eval_records_tenant_id'), table_name='eval_records')
    op.drop_index(op.f('ix_eval_records_run_id'), table_name='eval_records')
    op.drop_index(op.f('ix_eval_records_created_at'), table_name='eval_records')
    op.drop_table('eval_records')
    op.drop_index(op.f('ix_dev_workspaces_tenant_id'), table_name='dev_workspaces')
    op.drop_table('dev_workspaces')
    op.drop_index(op.f('ix_custom_roles_tenant_id'), table_name='custom_roles')
    op.drop_table('custom_roles')
    op.drop_index(op.f('ix_conversation_sessions_tenant_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_run_id'), table_name='conversation_sessions')
    op.drop_index('ix_conv_user_agent', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('app_secrets')
    op.drop_index(op.f('ix_agent_skills_tenant_id'), table_name='agent_skills')
    op.drop_index(op.f('ix_agent_skills_agent_id'), table_name='agent_skills')
    op.drop_table('agent_skills')
    op.drop_index(op.f('ix_agent_skill_toggles_tenant_id'), table_name='agent_skill_toggles')
    op.drop_table('agent_skill_toggles')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_tenant_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_agent_profiles_tenant_id'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_agent_id'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
    op.drop_index(op.f('ix_agent_call_logs_tenant_id'), table_name='agent_call_logs')
    op.drop_index(op.f('ix_agent_call_logs_run_id'), table_name='agent_call_logs')
    op.drop_index(op.f('ix_agent_call_logs_created_at'), table_name='agent_call_logs')
    op.drop_table('agent_call_logs')
    # ### end Alembic commands ###
