"""The Testing agent's two ends of the project's record: what it reads, what it files.

THE TESTING AGENT WAS BUILT BESIDE THE RECORD. Its test plan was derived from the
text of the user's sentence (or an upload), its upstream context was keyed by a
session id that a standalone chat never shares with Requirements or Design, and the
files it produced — the test plan, the QA report — were written to a session
directory and announced as download links, never recorded as project artifacts. So
a tester could not put a test case document forward for a Project Admin's approval,
Confluence had nothing approved to publish, and a new chat session deleted the
previous session's directory with the files in it.

Two functions, one per direction, both called from the chat entrypoint ON THE MAIN
LOOP (the graph's nodes run under `asyncio.run` in a worker thread, where the shared
asyncpg pool must not be touched):

  * `grounding(...)`   — what a standalone turn should know: the project's display
                          name, its approved documents as text (the BRD, the
                          design, the plan), and the latest per-stage payloads
                          (`upstream_requirements` etc.) resolved BY PROJECT, as
                          the Development agent resolves them;
  * `record_outputs(...)` — every document the run produced, filed as a DRAFT
                          testing-stage artifact so it appears in the page's
                          Documents list, can be submitted for approval, and
                          survives the session directory.
"""
from __future__ import annotations

import logging
import os
from typing import Any, Optional

logger = logging.getLogger("testing_agent.project_record")

#: Bounds for the approved documents' text folded into the plan prompt.
MAX_TOTAL_CHARS = 60_000
MAX_DOC_CHARS = 25_000

#: The stages whose approved documents a test plan is written against, in the order
#: they are folded in. Testing's own documents are not a source for themselves.
SOURCE_STAGES = ("requirements", "design", "plan", "development")

#: What a run may leave in its output directory that belongs in the record, with the
#: note an approver reads. Order matters: the first of each pair that exists wins.
RECORDED_OUTPUTS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("test_cases.docx",), "Test case document generated by the Testing agent."),
    (("test_plan.xlsx",), "Test cases as a spreadsheet — the working copy of the test case document."),
    (("qa_report.pdf", "qa_report.html"), "QA report for the test run."),
    (("ui_test_results.pdf", "ui_test_results.xlsx"), "UI test results."),
    (("coverage.html",), "Code coverage for the unit test run."),
)


async def grounding(tenant_id: str, project_id: str, *, consumer_run_id: Optional[str] = None) -> dict[str, Any]:
    """State keys for a standalone turn. Never raises; missing pieces are absent."""
    out: dict[str, Any] = {}
    if not (tenant_id and project_id):
        return out

    try:
        out["project_display_name"] = await _project_display_name(tenant_id, project_id)
    except Exception as exc:  # noqa: BLE001
        logger.info("testing grounding: project name unavailable (%s)", type(exc).__name__)

    try:
        text, source = await approved_documents_text(tenant_id, project_id, consumer_run_id=consumer_run_id)
        if text:
            out["approved_documents_text"] = text
            out["plan_source"] = source
    except Exception as exc:  # noqa: BLE001
        logger.warning("testing grounding: approved documents unavailable (%s)", type(exc).__name__, exc_info=True)

    try:
        from config.context_broker import _fetch_artifacts_for_project  # noqa: PLC0415

        payloads = await _fetch_artifacts_for_project(project_id, tenant_id) or {}
        if payloads.get("requirements_payload"):
            out["upstream_requirements"] = payloads["requirements_payload"]
        if payloads.get("design_artifacts"):
            out["upstream_design"] = payloads["design_artifacts"]
        # NOT the development payload. `classify_intent` treats an
        # `upstream_development` with a repo and branch as an Orchestrator handoff and
        # answers every message — "hi", "thanks" — with "Development is complete,
        # what testing would you like?". A standalone tester picks the branch in the
        # target dialog; the handoff shape stays the Orchestrator's.
        if any(k in out for k in ("upstream_requirements", "upstream_design")):
            out["upstream_loaded"] = True
    except Exception as exc:  # noqa: BLE001
        logger.info("testing grounding: upstream payloads unavailable (%s)", type(exc).__name__)
    return out


async def _project_display_name(tenant_id: str, project_id: str) -> str:
    import uuid as _uuid  # noqa: PLC0415

    from shared.db import get_db_session_for_tenant  # noqa: PLC0415
    from shared.models.orm import Project  # noqa: PLC0415

    async with get_db_session_for_tenant(tenant_id) as db:
        project = await db.get(Project, _uuid.UUID(str(project_id)))
        return (getattr(project, "display_name", "") or "") if project else ""


async def approved_documents_text(
    tenant_id: str, project_id: str, *, consumer_run_id: Optional[str] = None,
) -> tuple[str, str]:
    """(text, source line) — the project's approved documents from the source stages,
    each read through `read_document_for_agent` so the read is recorded as evidence.
    Empty when the project has none."""
    from shared.db import get_db_session_for_tenant  # noqa: PLC0415
    from shared.services.artifact_consumption import read_document_for_agent  # noqa: PLC0415
    from shared.services.artifact_versions import readable_documents  # noqa: PLC0415

    async with get_db_session_for_tenant(tenant_id) as db:
        docs = await readable_documents(db, project_id)

    chosen = [d for d in docs if (d.get("stage") in SOURCE_STAGES or d.get("stage") is None)]
    chosen.sort(key=lambda d: (
        SOURCE_STAGES.index(d["stage"]) if d.get("stage") in SOURCE_STAGES else len(SOURCE_STAGES),
        str(d.get("approvedAt") or ""),
    ))

    parts: list[str] = []
    names: list[str] = []
    used = 0
    for d in chosen:
        if used >= MAX_TOTAL_CHARS:
            break
        text, note = await read_document_for_agent(
            tenant_id=tenant_id, project_id=project_id, artifact_id=str(d.get("id") or ""),
            consumer_stage="testing", consumer_run_id=consumer_run_id,
        )
        if not text:
            logger.info("testing grounding: %s not readable: %s", d.get("title"), note)
            continue
        budget = min(MAX_DOC_CHARS, MAX_TOTAL_CHARS - used)
        body = text[:budget]
        if len(text) > budget:
            body += "\n[document continues beyond what was folded in]"
        title = str(d.get("title") or d.get("type") or "document")
        stage = str(d.get("stage") or "project")
        parts.append(f"=== {title} ({stage}, approved) ===\n{body}")
        names.append(title)
        used += len(body)

    if not parts:
        return "", ""
    return "\n\n".join(parts), "the project's approved documents: " + ", ".join(names)


async def record_outputs(output_directory: str, *, session_id: str, base_url: str, user_id: str,
                         already: dict[tuple[str, str], float]) -> list[str]:
    """File the run's documents as DRAFT testing-stage artifacts. Returns the names
    filed this time. `already` remembers (session, file) → mtime, so a follow-up chat
    turn that regenerates nothing files nothing twice."""
    from shared.services.chat_artifacts import register_generated_file  # noqa: PLC0415

    filed: list[str] = []
    for candidates, note in RECORDED_OUTPUTS:
        for name in candidates:
            path = os.path.join(output_directory, name)
            if not os.path.isfile(path):
                continue
            mtime = os.path.getmtime(path)
            if already.get((session_id, name)) == mtime:
                break
            url = f"{base_url}/generated/{user_id}/orchestrator/{session_id}/output/{name}"
            try:
                await register_generated_file(name, path, url, stage="testing", note=note)
                already[(session_id, name)] = mtime
                filed.append(name)
            except Exception as exc:  # noqa: BLE001 — never raises by contract, but be safe
                logger.warning("testing: could not record %s (%s)", name, type(exc).__name__)
            break
    return filed
